SEED:
  - 59
EPOCHS:
  - 1000
MAX_STEPS: # overwrites epochs. set to -1 if use epochs. Calculates the number of iteration -> depends on batch size
  - 5
BATCH_SIZE:
  - 4
LR:
  - 3e-5
MIN_LR:
  - 1e-5
DATA_PATH:
  - 'lilaspourpre/mt_dataset_train_all_test_sme'
USING_PEFT: # NOT USED
  - True
MODEL_TYPE: 
  - "M2M100"
MODEL_CHECKPOINT:
  - "facebook/m2m100_418M"
DATA_PARALLEL:
  - false
LOG_PRED_EVERY:
  - 1000
RUN_NAME:
- "test"
VAL_EVERY_EPOCH:
- 1
SAVE_EVERY:
- 1
SAVE_STRATEGY:
- 'epoch'
COMPUTE_METRICS_EVERY:
- 1
QLORA: # NOT USED
- true
TARGET_LANG:
- "fi"
NO_REPEAT_NGRAM:
- 0
SAMPLING:
- false
TEMPERATURE:
- 1
TOP_K:
- 250
NUM_BEAMS:
- 4
MAX_SEQ_LEN:
- 256
FL:
- false
ADAPTIVE_BATCH_SIZE:
- false
TOTAL_BATCH_SIZE:
- 512
MIN_BATCH_SIZE:
- 32
MAX_BATCH_SIZE:
- 128
FL_LR:
- 0.1
FL_NITERS:
- 5
AUX_ADAM:
- false
FL_BETA_1:
- 0
DROP_THRESHOLD:
- -1
ENABLE_FL_EVERY:
- -1
